{{- if .Values.blockscout.enabled }}
{{- if .Values.blockscout.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-blockscout-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # Name must match the name of the backend of blockscout
    name: {{ include "blockscout-stack.fullname" . }}-blockscout
  minReplicas: {{ .Values.blockscout.hpa.minReplicas }}
  maxReplicas: {{ .Values.blockscout.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.blockscout.hpa.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
